### ISSUE TITLE
Search highlight unreadable

### ISSUE THREAD

**Issue by misaflo** [0xD3BD/zathura-gruvbox#4]
Hi,

The search highlight is unreadable (don't remember since which version).

Not perfect, but adding transparency can make the text visible:

For gruvbox-dark:

    set highlight-color             rgba(250,189,47,0.5)
    set highlight-active-color      rgba(254,128,25,0.5)

zathura --version:

    zathura 0.5.8
    girara 0.4.4 (runtime: 0.4.4)
    (plugin) pdf-poppler (0.3.3) (/usr/lib/zathura/libpdf-poppler.so)

**Comment by eastack** [comment]
Thank you very much for your suggestion. I haven't used this software as my primary PDF reading tool for some time. However, once I have some time, I will standardize the colors to RGBA mode, which should resolve the issue.

**Comment by eastack** [comment]
The color format has been updated to RGBA, and the highlight color has been changed to semi-transparent. This issue should now be resolved.

**Comment by eastack** [comment]
0fbb6c94b5bcc8250e6edd4981f4f4991d28b94e
